

DESERT_TRAVEL_EVENTS = {
    1: "\n\n\n\n\n\n--------------------\nencounter\n--------------------\nCR: 2\nAC: 1 HP: 1 ATK: +2 DMG: +1 \n17 Scorpions\n\nLink: https://5e.tools/bestiary.html#scorpion_mm \n\n\n\n\n\n\n\n\n",
    2: "4 vultures",
    3: "1 abandoned mule",
    4: "6 commoners with 2d4 camels bound for a distant city",
    5: "6 flying snakes",
    6: "6 hyenas or 2d6 jackals",
    7: "6 guards escorting a noble to the edge of the desert, all of them astride camels",
    8: "6 cats",
    9: "1 pseudodragon",
    10: "4 Poisonous Snakes",
    11: "4 stirges",
    12: "4 Wolf Spiders",
    13: "1 Scout for a nameless organization",
    14: "4 giant poisonous snakes",
    15: "Single file boot tracks in the sand",
    16: "4 Kobolds",
    17: "1 Jackalwere",
    18: "6 tribale warriors",
    19: "6 Giant Lizards",
    20: "1 Swarm of Inscects",
    21: "An oasis surrounded by palm trees and containing the remnants of an old camp",
    22: "6 bandits",
    23: "4 constrictor snakes",
    24: "4 winged Kobolds",
    25: "1 dust mephit",
    26: "3 giant toads",
    27: "4 giant spiders",
    28: "1 druid, Druid named Academi he is a elf with a quest for the players to retrieve some stolen weapons, Offers 900GP (DC 18 Persuasion check for more money)",
    29: "4 Hobgoblins",
    30: "1 Wight",
    31: "1 Ogre and 1 el-goblino",
    32: "A single Brass Lamp on the ground, there is a faint oil trail (DC 20 Investigation check to find where the trail leads) the trail leads goes into a cave.",
    33: "One thing",
    34: "Plant pot",
}

SIZE_OF_DESERT = len(DESERT_TRAVEL_EVENTS)